# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
import_types = ["diesel::sql_types::*", "crate::code::CodeType as Passcode"]
generate_missing_sql_type_definitions = false

[migrations_directory]
dir = "./migrations"
